version: '3.3'
services: 
    herofrontend:
        build: ./heroes
        container_name: heroapp
        image: heroapp:1.0
        restart: always
        ports:
          - "3000:80"
    herobackend:
        build: ./heroesback
        container_name: heroserver
        image: heroserver:1.0
        restart: always
        ports:
            - "5000:5000"
        command: npm start

